name: Apt based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-buster
          - ubuntu-xenial
          - ubuntu-bionic
          - ubuntu-focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby
      - name: Build deb with Docker
        run: |
          rake apt:build APT_TARGETS=${{ matrix.os }}
      - uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.os }}
          path: td-agent/apt/repositories
