name: Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian GNU/Linux buster amd64
          - Ubuntu 18.04 bionic amd64
          - CentOS 7 amd64
          - CentOS 8 amd64
        include:
          - label: Debian GNU/Linux buster amd64
            id: debian-buster-amd64
            rake_arguments: apt:build APT_TARGETS=debian-buster
          - label: Ubuntu 18.04 bionic amd64
            id: ubuntu-bionic
            rake_arguments: apt:build APT_TARGETS=ubuntu-bionic
          - label: CentOS 7 amd64
            id: centos-7
            rake_arguments: yum:build YUM_TARGETS=centos-7
          - label: CentOS 8 amd64
            id: centos-8
            rake_arguments: yum:build YUM_TARGETS=centos-8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby
      - name: Build with docker
        run: |
          rake ${{ matrix.rake_arguments }}
