name: Yum based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-6
          - centos-7
          - centos-8
          - amazonlinux-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby
      - name: Build rpm with Docker
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.os }}
      - uses: actions/upload-artifact@master
        if: matrix.os == 'centos-6' || matrix.os == 'centos-7' || matrix.os == 'centos-8'
        with:
          name: packages-${{ matrix.os }}
          path: td-agent/yum/repositories
